QUEUE_LEN = 1
MAX_PACKET = 1024
IP = '0.0.0.0'
PORT = 1729
READ_SIZE = 1
REQUEST_TXT = 'The request received: '
ERR1 = 'client socket disconnected- '
ERR2 = 'failed to open server socket - '
END_OF_MESSAGE = '-'
END_OF_COMMUNICATION = 'x'
PLAYER_SEPERATOR = '#'
ID_SEPERATOR = ':'
